//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTemplete.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefreshToken
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Token { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public bool IsRevoked { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
